# Generated by Django 4.1.3 on 2022-11-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.JSONField()),
                ('address', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=200)),
                ('kakao_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('naver_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('google_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('menu', models.JSONField()),
                ('place_url', models.URLField()),
                ('review_url', models.URLField()),
            ],
        ),
    ]
