# Generated by Django 4.1.3 on 2022-11-20 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='naver_score',
            new_name='tripadvisor_score',
        ),
    ]
