# Generated by Django 4.1.3 on 2022-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_rename_naver_score_place_tripadvisor_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='google_score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='kakao_score',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='review_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tripadvisor_score',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='reviews',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='score',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='thumbnails',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_hours',
            field=models.JSONField(),
        ),
    ]
